{% set name = "pandamesh" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandamesh-{{ version }}.tar.gz
  sha256: c4e3efafb80687a66ffdf4cc3dc307dbed79fb5627ec0ee9dcc4057440a2900a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - geopandas
    - py-triangle
    - gmsh
    - python-gmsh
    - pooch
    - shapely >=2.0

test:
  imports:
    - pandamesh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deltares/pandamesh
  summary: From geodataframe to mesh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://deltares.github.io/pandamesh/
  dev_url: https://github.com/deltares/pandamesh

extra:
  recipe-maintainers:
    - Huite
    - JoerivanEngelen
    - visr
